// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz5k2rOE4bmzgMWBUqmtIY0S02p2od6Kg',
    appId: '1:1029716095379:web:d6aeab77e2baf73514f866',
    messagingSenderId: '1029716095379',
    projectId: 'auth-g9',
    authDomain: 'auth-g9.firebaseapp.com',
    storageBucket: 'auth-g9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9v7cuj_1TmL97tV2nUgdRtCoGJkeeHug',
    appId: '1:1029716095379:android:b863ff26e6591aec14f866',
    messagingSenderId: '1029716095379',
    projectId: 'auth-g9',
    storageBucket: 'auth-g9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyW3MMWfvie5VT5lUS06zPQI79KGoO858',
    appId: '1:1029716095379:ios:4ae01ccd4c50660714f866',
    messagingSenderId: '1029716095379',
    projectId: 'auth-g9',
    storageBucket: 'auth-g9.appspot.com',
    iosBundleId: 'com.example.group9Auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyW3MMWfvie5VT5lUS06zPQI79KGoO858',
    appId: '1:1029716095379:ios:511942dee61f5f3c14f866',
    messagingSenderId: '1029716095379',
    projectId: 'auth-g9',
    storageBucket: 'auth-g9.appspot.com',
    iosBundleId: 'com.example.group9Auth.RunnerTests',
  );
}
